// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbbXTkMq-eGICz8CwIyC74uSvm6hy_Mc4',
    appId: '1:802861908033:web:92f31540b2403300bb46c0',
    messagingSenderId: '802861908033',
    projectId: 'medical-b1ec4',
    authDomain: 'medical-b1ec4.firebaseapp.com',
    storageBucket: 'medical-b1ec4.firebasestorage.app',
    measurementId: 'G-9V5EJBSMN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgc03-6gvnRV61LVvi-GdsXomOeD1Bmwg',
    appId: '1:802861908033:android:5cb4b4924b1db9f0bb46c0',
    messagingSenderId: '802861908033',
    projectId: 'medical-b1ec4',
    storageBucket: 'medical-b1ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67hJjDR0WMVxgar0chNmfVzdBnSa5z88',
    appId: '1:802861908033:ios:39a568d3423ad9ebbb46c0',
    messagingSenderId: '802861908033',
    projectId: 'medical-b1ec4',
    storageBucket: 'medical-b1ec4.firebasestorage.app',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA67hJjDR0WMVxgar0chNmfVzdBnSa5z88',
    appId: '1:802861908033:ios:39a568d3423ad9ebbb46c0',
    messagingSenderId: '802861908033',
    projectId: 'medical-b1ec4',
    storageBucket: 'medical-b1ec4.firebasestorage.app',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbbXTkMq-eGICz8CwIyC74uSvm6hy_Mc4',
    appId: '1:802861908033:web:c239be75efceb85cbb46c0',
    messagingSenderId: '802861908033',
    projectId: 'medical-b1ec4',
    authDomain: 'medical-b1ec4.firebaseapp.com',
    storageBucket: 'medical-b1ec4.firebasestorage.app',
    measurementId: 'G-MYTBL6FEDJ',
  );
}
